### ISSUE TITLE
Failing $filter parser scenarios

### ISSUE THREAD

**Issue by PeterAronZentai** [jaystack/odata-parser#1]
- [ ] substring('ABCDEF', MemberField) 
- [ ] add(1, 1)   //add(Member, 1) works
- [ ] substringOf missing

**Comment by lazarv** [comment]
Error in ```substring``` parse caused by bad string literal parsing is fixed now.
Use ```1 add 1```, ```add``` is not a method call expression. It was parsed as a member expression (```add``` is a valid member expression), now throws error on unexpected token (which was a key value pair).
```substringof``` is not in the OData v4 standard ABNF, but it's included now in the parser.
